version: "3.1"

volumes:
  postgresql_data:

secrets:
  pg_postgres_password:
    file: ./secrets/pg_postgres_password.txt
  pg_django_password:
    file: ./secrets/pg_django_password.txt

services:
  database:
    image: mopnaej/ker51db:latest
    build: ./database
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_postgres_password
      - DJANGO_PASSWORD_FILE=/run/secrets/pg_django_password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    secrets:
      - pg_postgres_password
      - pg_django_password
    restart: always

