version: "2"

volumes:
  postgresql_data:
  django_static_files:

secrets:
  ker51_pg_postgres_password:
  ker51_pg_django_password:
  ker51_django_env:
  ker51_django_superuser_password:

services:
  database:
    image: mopnaej/ker51db:latest
    build: ./database
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/pg_postgres_password
      - DJANGO_PASSWORD_FILE=/run/secrets/pg_django_password
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    secrets:
      - ker51_pg_postgres_password
      - ker51_pg_django_password
    restart: always

  django:
    image: mopnaej/ker51webapp:latest
    build: ./django
#    command: ["sleep","10000"]
#    ports:
#      - 8001:8000
    environment:
      - DJANGO_ENV_FILE=/run/secrets/django_env
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - DJANGO_SUPERUSER_PASSWORD_FILE=/run/secrets/django_superuser_password
      - STATIC_ROOT=/static/
    volumes:
      - django_static_files:/static
    secrets:
      - ker51_django_env
      - ker51_django_superuser_password
    restart: always

  nginx:
#    image: nginx:alpine
    image: mopnaej/ker51nginx:latest
    build: ./nginx
#    ports:
#      - 80:80
    volumes:
      - django_static_files:/usr/share/nginx/html/static
#      - ./nginx/templates:/etc/nginx/templates
    environment:
     - NGINX_PUBLIC_HOST=ker51.pomfont.fr
     - NGINX_HOST=localhost
     - NGINX_PORT=80
    restart: always

