# Generated by Django 3.2.5 on 2021-07-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_rename_names_person_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='person_text',
        ),
    ]
