# Generated by Django 3.2.5 on 2021-07-29 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_name_person_person_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person_text',
            new_name='names',
        ),
    ]
