# Generated by Django 3.2.5 on 2021-07-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_person_text_person_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='emails',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='fulladdress',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='person',
            name='phones',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='pub_date',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
    ]
