# Generated by Django 3.2.5 on 2021-07-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_alter_person_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
