# Generated by Django 3.2.5 on 2021-07-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_alter_person_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
