# Generated by Django 3.2.5 on 2021-07-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_person_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emails',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='phones',
            field=models.TextField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='trognes/'),
        ),
    ]
