# Generated by Django 3.2.5 on 2021-07-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_auto_20210730_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='emails',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='phones',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
