# Generated by Django 3.2.5 on 2021-07-30 20:29

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20210730_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
