# Generated by Django 3.2.5 on 2021-08-01 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivernants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='email',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='email'),
        ),
    ]
