# Generated by Django 3.2.5 on 2021-08-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivernants', '0003_alter_email_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='hivernant',
            name='mission_number',
            field=models.SmallIntegerField(default=51, verbose_name='Mission'),
        ),
    ]
