# Generated by Django 3.2.5 on 2021-08-01 07:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=200, verbose_name='Nom(s)')),
                ('fulladdress', models.TextField(blank=True, default='', verbose_name='Adresse')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Lieu')),
                ('comments', models.TextField(blank=True, default='', verbose_name='Commentaires')),
                ('picture', models.ImageField(blank=True, default='', upload_to='trognes/', verbose_name='photo')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Hivernant',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hivernants.person')),
            ],
            bases=('hivernants.person',),
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Téléphone')),
                ('comment', models.CharField(blank=True, default='', max_length=50, verbose_name='Commentaire')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivernants.hivernant')),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default='', max_length=20, verbose_name='email')),
                ('comment', models.CharField(blank=True, default='', max_length=50, verbose_name='Commentaire')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hivernants.hivernant')),
            ],
        ),
    ]
